name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8 pytest requests
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv  # the --user should be removed if you do this in a venv
          pip3 install --user --upgrade buildozer
        
      - name: Install dependencies
        run: buildozer android debug --android.accept-licenses
        id: buildozer
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
